### ISSUE TITLE
Does the settings not support multiple drivers loading at the same time ?

### ISSUE THREAD

**Issue by osguydch** [containerops/wrench#18]
I just saw the code as  bellowing at wrench/setting/setting.go :

// object storage driver config parameters
// TBD: It should be considered to refine the universal config parameters
var (
	Endpoint        string
	Bucket          string
	AccessKeyID     string
	AccessKeysecret string

	//upyun unique
	User   string
	Passwd string

these are global vars, isn't it ?

**Comment by genedna** [comment]
ping @MabinGo

**Comment by MabinGo** [comment]
@osguydch One Dockyard instance supports user to run single object storage driver at the same time, the driver must be specified in "conf/runtime.conf",so in wrench,we do it according to Dockyard design. Currently there are no scenarios to run multiple drivers at the same time,but we can consider these scenarios when we do coding design.

**Comment by osguydch** [comment]
ok, let it go.
